version: "3"

services:
  dev-nginx:
    container_name: dev-nginx
    build:
      context: ./.docker/dev/nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${NGINX_SSL_PORT}:${NGINX_SSL_PORT}
    volumes:
      - ./client/public:/usr/share/nginx/html
    depends_on:
      - dev-server
      - dev-mapproxy

  dev-server:
    container_name: dev-server
    build:
      context: ./.docker/dev/server
    ports:
      - "8082:8082"
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    command: npm run start

  dev-client:
    container_name: dev-client
    build:
      context: ./.docker/dev/client
    ports:
      - "8081:8081"
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    command: npm run serve
    depends_on:
      - dev-server

  dev-geoserver:
    container_name: dev-geoserver
    build:
      context: ./.docker/dev/geoserver
    ports:
      - ${GEOSERVER_PORT}:${GEOSERVER_PORT}
    volumes:
      - ./geoserver:/geoserver
      - ./geoserver/data_dir:/var/local/geoserver

  dev-mapproxy:
    container_name: dev-mapproxy
    build:
      context: ./.docker/dev/mapproxy
    volumes:
      - ./mapproxy:/mapproxy
