version: "3"

services:
  dev-nginx:
    container_name: dev-nginx
    build:
      context: ./.docker/dev/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./client/public:/usr/share/nginx/html
    depends_on:
      - dev-mapproxy
      - dev-geoserver

  dev-database:
    container_name: dev-database
    build:
      context: './.docker/dev/database'
    restart: always
    environment:
      POSTGRES_DBNAME: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
      ALLOW_IP_RANGE: 0.0.0.0/0
    volumes:
      # - ./postgres_data:/var/lib/postgresql/data
      - ./database/setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
    ports:
      - 5435:5432

  dev-geoserver:
    container_name: dev-geoserver
    build:
      context: ./.docker/dev/geoserver
    ports:
      - 8080:8080
    volumes:
      - ./geoserver:/geoserver
      - ./geoserver/data_dir:/var/local/geoserver

  dev-mapproxy:
    container_name: dev-mapproxy
    build:
      context: ./.docker/dev/mapproxy
    volumes:
      - ./mapproxy:/mapproxy
