version: "3"

# NOTE: Database needs to be running in order to run following container

services:
  nominatim-setup:
    build:
      context: ./nominatim
    volumes:
      - ./data/osm_data:/app/osm_data
      - ./nominatim:/nominatim
    command: /bin/sh -c "/app/init.sh Helsinki.osm.pbf"
