version: "3"

# NOTE: Database needs to be running in order to run following containers

services:
  osm2pgrouting:
    build:
      context: ./osm2pgrouting
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: 5435
      POSTGRES_IMPORT_SCHEMA: "routing_osm"
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/osm_data:/osm_data
    network_mode: host
      
  digiroad2pgrouting:
    build:
      context: ./digiroad2pgrouting
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: 5435
      POSTGRES_IMPORT_SCHEMA: "routing_digiroad"
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/digiroad_data:/digiroad_data
    network_mode: host
