version: "3"

services:
  dev-nginx:
    container_name: dev-nginx
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./client/public:/usr/share/nginx/html
    depends_on:
      - dev-mapproxy
      - dev-geoserver

  dev-database:
    container_name: dev-database
    image: kartoza/postgis:12.0
    restart: always
    environment:
      POSTGRES_DBNAME: gis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,pgrouting
      ALLOW_IP_RANGE: 0.0.0.0/0
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
    ports:
      - 5435:5432

  dev-geoserver:
    container_name: dev-geoserver
    image: oscarfonts/geoserver
    ports:
      - 8080:8080
    volumes:
      - ./geoserver/data_dir:/var/local/geoserver
      - ./geoserver/exts_dir:/var/local/geoserver-exts/

  dev-mapproxy:
    container_name: dev-mapproxy
    build:
      context: ./mapproxy
    volumes:
      - ./mapproxy:/mapproxy

  # NOTE THAT /app/init.sh needs to be run to get data into db
  # see nominatim/README.md for more info

  dev-nominatim:
    container_name: dev-nominatim
    build:
      context: ./nominatim
    ports:
      - 7070:8100
    volumes:
      - ./nominatim:/nominatim
    command: /bin/sh -c "/app/startapache.sh"
    depends_on:
      - dev-database

volumes:
  postgres_data: