version: "3"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./client/public:/usr/share/nginx/html
    depends_on:
      - client
      - server
      - mapproxy
      - geoserver
      - nominatim

  client:
    build:
      context: ./client
    ports:
      - 8082:8082

  server:
    build:
      context: ./server
    ports:
      - 8085:8085
    depends_on:
      - database

  database:
    image: kartoza/postgis:12.0
    restart: always
    environment:
      POSTGRES_DBNAME: gis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,pgrouting
      ALLOW_IP_RANGE: 0.0.0.0/0
    volumes:
      - postgres_data:/var/lib/postgresql
      # Uncomment this to allow initial sql scripts to be run on initial db setup
      # - ./database/setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
      - nominatim_config:/app/src/build/module
    ports:
      - 5435:5432

  geoserver:
    image: oscarfonts/geoserver
    ports:
      - 8080:8080
    volumes:
      - ./geoserver/data_dir:/var/local/geoserver
      - ./geoserver/exts_dir:/var/local/geoserver-exts/
    depends_on:
      - database

  mapproxy:
    build:
      context: ./mapproxy
    volumes:
      - ./mapproxy:/mapproxy

  nominatim:
    build:
      context: ./nominatim
    ports:
      - 7070:8100
    volumes:
      - ./nominatim:/nominatim
      - nominatim_config:/app/src/build/module
    command: /bin/sh -c "/app/startapache.sh"
    depends_on:
      - database

volumes:
  postgres_data:
  nominatim_config:
