version: "3"

services:
  dev-nginx:
    container_name: dev-nginx
    build:
      context: ./.docker/dev/nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${NGINX_SSL_PORT}:${NGINX_SSL_PORT}
    volumes:
      - ./client/public:/usr/share/nginx/html
    depends_on:
      - dev-server
      - dev-mapproxy
      - dev-geoserver

  dev-database:
    container_name: dev-database
    build:
      context: './.docker/dev/database'
    restart: always
    environment:
      POSTGRES_DBNAME: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
      ALLOW_IP_RANGE: 0.0.0.0/0
    volumes:
      # - ./postgres_data:/var/lib/postgresql/data
      - ./database/setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
    ports:
      - 5435:5432

  dev-server:
    container_name: dev-server
    build:
      context: ./server
    ports:
      - 8085:8085
    volumes:
      # - ./server:/server
      - ./server/node_modules:/server/node_modules
    command: npm run start
    depends_on:
      - dev-database

  # dev-client:
  #   container_name: dev-client
  #   build:
  #     context: ./client
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./client:/client
  #     - ./client/node_modules:/client/node_modules
  #   command: npm run serve
  #   depends_on:
  #     - dev-server

  dev-geoserver:
    container_name: dev-geoserver
    build:
      context: ./.docker/dev/geoserver
    ports:
      - ${GEOSERVER_PORT}:${GEOSERVER_PORT}
    volumes:
      - ./geoserver:/geoserver
      - ./geoserver/data_dir:/var/local/geoserver

  dev-mapproxy:
    container_name: dev-mapproxy
    build:
      context: ./.docker/dev/mapproxy
    volumes:
      - ./mapproxy:/mapproxy
