#!/bin/bash

PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USERNAME -h $POSTGRES_HOST -p $POSTGRES_PORT $POSTGRES_DBNAME -tAc "CREATE SCHEMA IF NOT EXISTS $POSTGRES_IMPORT_SCHEMA"
PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USERNAME -h $POSTGRES_HOST -p $POSTGRES_PORT $POSTGRES_DBNAME -tAc "DROP TABLE IF EXISTS $POSTGRES_IMPORT_SCHEMA.digiroad"
PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USERNAME -h $POSTGRES_HOST -p $POSTGRES_PORT $POSTGRES_DBNAME -tAc "DROP TABLE IF EXISTS $POSTGRES_IMPORT_SCHEMA.digiroad_vertices_pgr"
PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USERNAME -h $POSTGRES_HOST -p $POSTGRES_PORT $POSTGRES_DBNAME -tAc "DROP TABLE IF EXISTS $POSTGRES_IMPORT_SCHEMA.digiroad_nopeusrajoitus"

for dir in digiroad_data/* ; do
  ogr2ogr -update -append -a_srs EPSG:3067 \
    -nlt LINESTRING -lco GEOMETRY_NAME=geom -lco FID=id -lco SCHEMA=$POSTGRES_IMPORT_SCHEMA \
    -f PostgreSQL "PG:host=$POSTGRES_HOST port=$POSTGRES_PORT user=$POSTGRES_USERNAME dbname=$POSTGRES_DBNAME password=$POSTGRES_PASSWORD" $dir/DR_LINKKI_K.shp \
    -nln $POSTGRES_IMPORT_SCHEMA.digiroad

  ogr2ogr -update -append -a_srs EPSG:3067 \
    -nlt LINESTRING -lco GEOMETRY_NAME=geom -lco FID=id -lco SCHEMA=$POSTGRES_IMPORT_SCHEMA \
    -f PostgreSQL "PG:host=$POSTGRES_HOST port=$POSTGRES_PORT user=$POSTGRES_USERNAME dbname=$POSTGRES_DBNAME password=$POSTGRES_PASSWORD" $dir/DR_NOPEUSRAJOITUS_K.shp \
    -nln $POSTGRES_IMPORT_SCHEMA.digiroad_nopeusrajoitus
done

PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USERNAME -h $POSTGRES_HOST -p $POSTGRES_PORT $POSTGRES_DBNAME < sql/pgrouting_setup.sql
